### PR TITLE
Add 'not dead' browser compatibility. fixes #14

### LINKED ISSUE #14: Include ES6 synatx in dist

### PR DESCRIPTION
**Pull request by Hacklone**

### CODE REVIEW

**Comment by Hacklone** [comment]
Did anyone has chance to take a look at this issue?

**Comment by dadouam** [comment]
Thanks for this, I hope it will be merged into the main repo soon because the package is currently unusable with IE11.

**Comment by webmatth** [comment]
My PR could be related to this #23 
apparently, v4.0.0 of normalize-url is needed, not v4.5.0
https://github.com/sindresorhus/normalize-url#install

**Comment by visualjerk** [comment]
Sorry for the late response. I need to turn on notifications for this repo again 😄 

This fix is now available with version `2.0.1`.

**Comment by Hacklone** [comment]
No problem :) Thanks for merging

**Pull request merged**
